Algoritmo "AreaRetangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriella
// Data atual  : 16/03/2025
Var
// Seção de Declarações das variáveis 
altura:inteiro
base: inteiro
area:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo